name: Write Timestamp Action

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour

  workflow_dispatch:

jobs:
  write-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Write current timestamp to file
        run: python scripts/test_gh_actions.py

      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add timestamp.txt
          git commit -m "Update timestamp" -a || echo "No changes to commit"
          git push
