name: Write Timestamp Action

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the first day of every month

  workflow_dispatch:

jobs:
  write-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Write current timestamp to file
        run: python update_datasets.py

      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -m "Update timestamp" -a || echo "No changes to commit"
          git push
